const series=[
  {id:'pinyin',label:'拼音',en:'PINYIN',description:'把声母、韵母、声调和拼读规则做成一张张可以反复练习的教学卡片。'},
  {id:'math-teacher',label:'数学',en:'MATH TEACHER',description:'让抽象的函数、金额和时间关系，变成可以被看见、被理解的动态演示。'}
];
const works=[
  {id:'pinyin-01-aoe',title:'单韵母 a o e',en:'Pinyin / Lesson 01',series:'pinyin',image:'assets/covers/pinyin-01-aoe.png',tags:['a o e','四声'],prompt:'汉语拼音教学卡片，部编一年级上册第1课「a o e」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 01 · 2026 / 09 / 20',caption:'今天：a o e，挂上四声就会读。',note:'pinyin-tone-placement'},
  {id:'pinyin-02-iuu',title:'单韵母 i u ü',en:'Pinyin / Lesson 02',series:'pinyin',image:'assets/covers/pinyin-02-iuu.png',tags:['i u ü','四声'],prompt:'汉语拼音教学卡片，部编一年级上册第2课「i u ü」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 02 · 2026 / 09 / 21',caption:'今天：i u ü，挂上四声就会读。',note:'pinyin-tone-placement'},
  {id:'pinyin-03-bpmf',title:'声母 b p m f',en:'Pinyin / Lesson 03',series:'pinyin',image:'assets/covers/pinyin-03-bpmf.png',tags:['b p m f','拼读'],prompt:'汉语拼音教学卡片，部编一年级上册第3课「b p m f」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 03 · 2026 / 09 / 22',caption:'今天：声母 b p m f，和 a 拼起来读。',note:'pinyin-spelling'},
  {id:'pinyin-04-dtnl',title:'声母 d t n l',en:'Pinyin / Lesson 04',series:'pinyin',image:'assets/covers/pinyin-04-dtnl.png',tags:['d t n l','拼读'],prompt:'汉语拼音教学卡片，部编一年级上册第4课「d t n l」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 04 · 2026 / 09 / 23',caption:'今天：声母 d t n l，和 a 拼起来读。',note:'pinyin-spelling'},
  {id:'pinyin-05-gkh',title:'声母 g k h',en:'Pinyin / Lesson 05',series:'pinyin',image:'assets/covers/pinyin-05-gkh.png',tags:['g k h','拼读'],prompt:'汉语拼音教学卡片，部编一年级上册第5课「g k h」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 05 · 2026 / 09 / 26',caption:'今天：声母 g k h，和 uā 拼起来读（瓜 / 夸 / 花）。',note:'pinyin-spelling'},
  {id:'pinyin-06-jqx',title:'声母 j q x',en:'Pinyin / Lesson 06',series:'pinyin',image:'assets/covers/pinyin-06-jqx.png',tags:['j q x','拼读'],prompt:'汉语拼音教学卡片，部编一年级上册第6课「j q x」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 06 · 2026 / 09 / 27',caption:'今天：声母 j q x，和 iā 拼起来读（家 / 掐 / 虾）。',note:'pinyin-spelling'},
  {id:'pinyin-07-zcs',title:'声母 z c s',en:'Pinyin / Lesson 07',series:'pinyin',image:'assets/covers/pinyin-07-zcs.png',tags:['z c s','拼读'],prompt:'汉语拼音教学卡片，部编一年级上册第7课「z c s」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 07 · 2026 / 09 / 29',caption:'今天：平舌 z c s——本音轻短（兹/刺/嘶），zi/ci/si 才是资/次/思。',note:'pinyin-spelling'},
  {id:'pinyin-08-zhchshr',title:'声母 zh ch sh r',en:'Pinyin / Lesson 08',series:'pinyin',image:'assets/covers/pinyin-08-zhchshr.png',tags:['zh ch sh r','翘舌音'],prompt:'汉语拼音教学卡片，部编一年级上册第8课「zh ch sh r」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 08 · 2026 / 09 / 28',caption:'今天：声母 zh ch sh r（翘舌），拼 zhā / chā / shā，还有 rì（日）。',note:'pinyin-spelling'},
  {id:'pinyin-09-yw',title:'y、w 的拼写规则',en:'Pinyin / Lesson 09',series:'pinyin',image:'assets/covers/pinyin-09-yw.png',tags:['y w','整体认读'],prompt:'汉语拼音教学卡片，部编一年级上册第9课「y w」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 09 · 2026 / 10 / 02',caption:'今天：y w——i 行前加 y（yi 衣），u 行前加 w（wu 乌）；整体认读记得写法。',note:'pinyin-spelling'},
  {id:'pinyin-10-aieiui',title:'复韵母 ai ei ui',en:'Pinyin / Lesson 10',series:'pinyin',image:'assets/covers/pinyin-10-aieiui.png',tags:['ai ei ui','四声'],prompt:'汉语拼音教学卡片，部编一年级上册第10课「ai ei ui」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 10 · 2026 / 10 / 02',caption:'今天：复韵母 ai ei ui——一口气滑过去；方案大声词哀 / 欸 / 威（ui←uei）。',note:'pinyin-spelling'},
  {id:'pinyin-11-aoouiu',title:'复韵母 ao ou iu',en:'Pinyin / Lesson 11',series:'pinyin',image:'assets/covers/pinyin-11-aoouiu.png',tags:['ao ou iu','四声'],prompt:'汉语拼音教学卡片，部编一年级上册第11课「ao ou iu」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 11 · 2026 / 10 / 02',caption:'今天：复韵母 ao ou iu——一口气滑过去；方案大声词熬 / 欧 / 优（iu←iou）。',note:'pinyin-spelling'},
  {id:'pinyin-12-ieueer',title:'复韵母 ie üe er',en:'Pinyin / Lesson 12',series:'pinyin',image:'assets/covers/pinyin-12-ieueer.png',tags:['ie üe er','四声'],prompt:'汉语拼音教学卡片，部编一年级上册第12课「ie üe er」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 12 · 2026 / 10 / 02',caption:'今天：ie üe er——耶 / 约 / 儿；er 舌头往后卷轻轻一拐。',note:'pinyin-spelling'},
  {id:'pinyin-13-anen',title:'鼻韵母 an en in un ün',en:'Pinyin / Lesson 13',series:'pinyin',image:'assets/covers/pinyin-13-anen.png',tags:['an en in un ün','鼻韵母'],prompt:'汉语拼音教学卡片，部编一年级上册第13课「an en in un ün」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 13 · 2026 / 10 / 02',caption:'今天：前鼻韵母 an en in un ün——安/恩/因；un←uen 联想温，ün 晕。',note:'pinyin-spelling'},
  {id:'pinyin-14-angeng',title:'鼻韵母 ang eng ing ong',en:'Pinyin / Lesson 14',series:'pinyin',image:'assets/covers/pinyin-14-angeng.png',tags:['ang eng ing ong','后鼻韵母'],prompt:'汉语拼音教学卡片，部编一年级上册第14课「ang eng ing ong」，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · 部编课 14 · 2026 / 10 / 02',caption:'今天：后鼻韵母 ang eng ing ong——昂/英；eng 是亨的韵母，ong 是轰的韵母。',note:'pinyin-spelling'},
  {id:'math-sine-function',title:'正弦函数的形状',en:'Math Teacher / Sine Function',series:'math-teacher',image:'assets/covers/sin-function-verify-mid.jpg',videoUrl:'assets/videos/sin-function.mp4',videoLabel:'正弦函数视频',tags:['函数','动态可视化'],prompt:'数学教学动画，逐步解释正弦函数的图像，清晰坐标轴、周期、振幅和相位，明亮课堂配色，节奏准确',negative:'坐标轴模糊，标签难读，水印，信息拥挤',model:'Math Teacher',params:'MP4 · 1280 × 900 · 12s',caption:'让曲线动起来，周期、振幅和相位就不再只是公式里的词。',note:'math-motion'},
  {id:'math-rmb-learning',title:'认识人民币',en:'Math Teacher / RMB',series:'math-teacher',image:'assets/covers/rmb-learning-title.jpg',videoUrl:'assets/videos/rmb-learning.mp4',videoLabel:'人民币学习视频',tags:['数学启蒙','生活数学'],prompt:'数学启蒙教学动画，认识人民币面额并进行生活化比较和换算，步骤清楚，适合儿童理解',negative:'金额标注错误，文字难读，水印，节奏过快',model:'Math Teacher',params:'MP4 · 1280 × 720 · 40s',caption:'把金额放回真实生活场景里，比较、换算和使用就有了具体的入口。',note:'math-motion'},
  {id:'math-clock-learning',title:'认识整点',en:'Math Teacher / Clock',series:'math-teacher',image:'assets/covers/clock-learning-title.jpg',videoUrl:'assets/videos/clock-learning-zhengdian.mp4',videoLabel:'认识整点视频',tags:['时间','整点'],prompt:'数学启蒙教学动画，认识钟面和整点时刻，时针分针关系清晰，逐步演示，友好的课堂视觉',negative:'指针位置错误，时间标注错误，水印，背景杂乱',model:'Math Teacher',params:'MP4 · 1280 × 900 · 23s',caption:'从钟面上的两根指针开始，把“整点”变成可以看见和说出的时间关系。',note:'math-motion'}
];
const notes=[
  {id:'pinyin-tone-placement',title:'声调先看位置，再听声音',date:'2026 / 09',type:'拼音方法',intro:'把四声放回韵母上，读音、字形和记忆就有了同一个落点。',body:'制作拼音卡片时，先保证韵母和声调的关系足够清楚，再处理装饰和颜色。孩子可以先看声调位置，再跟着卡片读出来；视觉线索越稳定，复习时越容易自我检查。'},
  {id:'pinyin-spelling',title:'拼读卡片要留出连接感',date:'2026 / 09',type:'拼音方法',intro:'声母、韵母和声调不是三个孤立标签，而是一条可以跟读的声音路径。',body:'一张好的拼读卡片需要让视线从声母自然走到韵母，再落到完整音节。文字不要堆满，示例也不要一次放太多，给孩子留下“连起来读”的空间。'},
  {id:'math-motion',title:'让数学关系动起来',date:'2026 / 10',type:'数学演示',intro:'函数、金额和时间都可以先变成动作，再回到定义和规则。',body:'数学演示先给出一个可观察的变化：曲线沿坐标轴移动、金额在生活场景里组合、指针走到整点。观众先看到关系，再用文字命名它，抽象概念就有了可回看的入口。'}
];
function seriesOf(w){return series.find(s=>s.id===w.series)||series[0]}
function card(w){const s=seriesOf(w);return `<a class="work-card" href="work-detail.html?id=${w.id}" data-series="${w.series}" data-tags="${w.tags.join(' ')}"><div class="work-image"><img src="${w.image}" alt="${w.title} ${s.label}"></div><div class="work-meta"><div><div class="series-label">${s.label}</div><div class="work-title">${w.title}</div>${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><span class="work-index">${String(works.indexOf(w)+1).padStart(2,'0')}</span></div></a>`}
function filterButtons(){return `<button class="filter selected" data-series-filter="all">全部</button>${series.map(s=>`<button class="filter" data-series-filter="${s.id}">${s.label}</button>`).join('')}`}
function initNav(){const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===path||(!path&&a.getAttribute('href')==='index.html'))a.classList.add('active')});const m=document.querySelector('.menu');if(m)m.onclick=()=>document.querySelector('.nav').classList.toggle('open')}
function bindFilters(root,selector='.work-card'){if(!root)return;const buttons=root.querySelectorAll('[data-series-filter]');const cards=root.querySelectorAll(selector);const apply=f=>{buttons.forEach(b=>b.classList.toggle('selected',b.dataset.seriesFilter===f));cards.forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.series!==f));root.querySelectorAll('.series-group').forEach(g=>{const visible=[...g.querySelectorAll('.work-card')].some(c=>!c.classList.contains('hidden'));g.classList.toggle('hidden',!visible)});};buttons.forEach(b=>b.onclick=()=>apply(b.dataset.seriesFilter));return apply}
function renderHome(){const el=document.querySelector('#featured');if(el)el.innerHTML=works.map(card).join('');const home=bindFilters(document.querySelector('#home-archive'));if(home)home(new URLSearchParams(location.search).get('series')||'all');const np=document.querySelector('#notes-preview');if(np)np.innerHTML=notes.map(n=>`<a class="note-item" href="note.html?id=${n.id}"><div class="meta">${n.date} · ${n.type}</div><h3>${n.title}</h3><p>${n.intro}</p></a>`).join('')}
function renderWorks(){const root=document.querySelector('#works-archive');if(!root)return;const gallery=document.querySelector('#gallery');gallery.innerHTML=series.map(s=>{const items=works.filter(w=>w.series===s.id);return `<section class="series-group" data-series-group="${s.id}"><div class="series-heading"><div><div class="eyebrow">${s.en}</div><h2>${s.label}</h2></div><p>${s.description}</p></div><div class="gallery-group">${items.map(card).join('')}</div></section>`}).join('');const apply=bindFilters(root);apply(new URLSearchParams(location.search).get('series')||'all')}
function renderDetail(){const root=document.querySelector('#detail');if(!root)return;const w=works.find(x=>x.id===new URLSearchParams(location.search).get('id'))||works[0];const s=seriesOf(w);document.title=`${w.title} — 溜溜数算 · 影像`;const media=w.videoUrl?`<div class="detail-media"><video controls preload="metadata" poster="${w.image}"><source src="${w.videoUrl}" type="video/mp4">你的浏览器不支持视频播放。</video><p class="media-note">${w.videoLabel||'教学演示视频'}。视频与封面都使用相对路径，放在站点 assets 目录中。</p></div>`:`<img class="detail-hero" src="${w.image}" alt="${w.title}">`;root.innerHTML=`<div class="detail-head"><div><div class="eyebrow">${s.en} / Selected work / ${String(works.indexOf(w)+1).padStart(2,'0')}</div><h1>${w.title}</h1><div><span class="series-pill">${s.label}</span>${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><p class="detail-lead">${w.caption}</p></div>${media}<div class="detail-columns"><div><h2>Prompt / 提示词</h2><div class="prompt-box"><p class="prompt-text">${w.prompt}</p><button class="copy-button" data-copy="${w.prompt.replaceAll('"','&quot;')}">复制提示词</button></div>${w.negative?`<div class="detail-note"><b>Negative prompt</b><br>${w.negative}</div>`:''}</div><div><h2>制作记录</h2><div class="specs"><div class="spec"><span>系列 / Series</span><b>${s.label}</b></div><div class="spec"><span>模型 / Model</span><b>${w.model}</b></div><div class="spec"><span>参数 / Params</span><b>${w.params}</b></div><div class="spec"><span>关键词</span><b>${w.tags.join(' · ')}</b></div>${w.videoUrl?`<div class="spec"><span>视频来源</span><b>assets/videos</b></div>`:''}</div><div class="detail-note">这件作品是「溜溜数算 · 影像」的教学视觉样本。记录参数，不是为了复刻，而是为了保留下一次创作的入口。<br><br><a class="text-link" href="note.html?id=${w.note}">阅读相关笔记 →</a></div></div></div>`;const copy=root.querySelector('.copy-button');if(copy)copy.onclick=async e=>{await navigator.clipboard.writeText(e.currentTarget.dataset.copy);e.currentTarget.textContent='已复制 ✓';e.currentTarget.classList.add('done');setTimeout(()=>{e.currentTarget.textContent='复制提示词';e.currentTarget.classList.remove('done')},1800)}}
function renderNotes(){const el=document.querySelector('#notes-list');if(el)el.innerHTML=notes.map(n=>`<a class="note-row" href="note.html?id=${n.id}"><div class="meta">${n.date}</div><div><h2>${n.title}</h2><div class="meta">${n.type}</div></div><p>${n.intro}</p></a>`).join('')}
function renderNote(){const el=document.querySelector('#note-content');if(!el)return;const n=notes.find(x=>x.id===new URLSearchParams(location.search).get('id'))||notes[0];document.title=`${n.title} — 溜溜数算 · 影像`;el.innerHTML=`<div class="eyebrow">Field note / ${n.date}</div><h1>${n.title}</h1><p class="lede">${n.intro}</p><div class="meta">${n.type} · 溜溜数算</div><h2>先从关系开始</h2><p>${n.body}</p><blockquote>“好的教学视觉，不是把一切都说满，而是为观察和跟读留下空间。”</blockquote><h2>一个小练习</h2><p>打开最近的一张卡片或一段演示，先不看细节，只写下三个词：一个对象词、一个变化词、一个检查词。用它们复述画面，再只替换其中一层。重复三次，你会看到概念如何在同一条线索上变得清楚。</p><p><a class="text-link" href="works.html">回到作品库 →</a></p>`}
document.addEventListener('DOMContentLoaded',()=>{initNav();renderHome();renderWorks();renderDetail();renderNotes();renderNote()});
