const series=[
  {id:'pinyin',label:'拼音',en:'PINYIN',description:'把声母、韵母、声调和拼读规则做成一张张可以反复练习的教学卡片。'},
  {id:'math-teacher',label:'数学',en:'MATH TEACHER',description:'让抽象的函数、金额和时间关系，变成可以被看见、被理解的动态演示。'}
];
const works=[
  {id:'pinyin-vowels-tones',title:'单韵母与四声',en:'Pinyin / Vowels & Tones',series:'pinyin',image:'assets/covers/pinyin-vowels-tones.png',tags:['a o e','四声'],prompt:'汉语拼音教学卡片，单韵母 a o e 与四声标调，清楚的字形层级，适合儿童跟读和复习，留白充足，平面教学视觉',negative:'字形模糊，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · lesson 01 · 2026 / 09 / 20',caption:'先把 a、o、e 读稳，再把四声挂上去，声调就有了可以观察的形状。',note:'pinyin-tone-placement'},
  {id:'pinyin-initials-spell',title:'声母拼读：b p m f',en:'Pinyin / Initials',series:'pinyin',image:'assets/covers/pinyin-initials-spell.png',tags:['b p m f','拼读'],prompt:'汉语拼音声母教学卡片，b p m f 与 a 的拼读示例，注音清晰，口型和拼读节奏易于跟读，儿童教育信息图',negative:'错误拼音，难以辨认的注音，水印，拥挤排版',model:'Pinyin Daily',params:'PNG · lesson 03 · 2026 / 09 / 22',caption:'把声母和韵母连起来，拼读不再是背诵，而是一次次能听见的合成。',note:'pinyin-spelling'},
  {id:'pinyin-zh',title:'翘舌音 zh',en:'Pinyin / zh',series:'pinyin',image:'assets/covers/pinyin-zh.png',tags:['zh ch sh r','翘舌音'],prompt:'汉语拼音声母教学卡片，zh 的发音与拼读示例，突出舌位提示和声调，清爽、可打印的课堂视觉',negative:'发音标注错误，低对比度，水印，复杂背景',model:'Pinyin Daily',params:'PNG · lesson 09 · 2026 / 09 / 28',caption:'翘舌音需要慢下来听和看：先认清 zh，再把它放进完整音节里。',note:'pinyin-spelling'},
  {id:'pinyin-compounds-tones',title:'复韵母 ai ei ui',en:'Pinyin / Compound Finals',series:'pinyin',image:'assets/covers/pinyin-compounds-tones.png',tags:['ai ei ui','四声'],prompt:'汉语拼音复韵母教学卡片，ai ei ui 的滑动发音与四声练习，清楚的拼音字母、声调和儿童课堂版式',negative:'拆读成单韵母，错误声调，文字重叠，水印',model:'Pinyin Daily',params:'PNG · lesson 11 · 2026 / 09 / 30',caption:'复韵母要一口气滑过去，ai、ei、ui 的声音是连在一起的。',note:'pinyin-spelling'},
  {id:'pinyin-nasal-tones',title:'鼻韵母 an en in',en:'Pinyin / Nasal Finals',series:'pinyin',image:'assets/covers/pinyin-nasal-tones.png',tags:['an en in','鼻韵母'],prompt:'汉语拼音鼻韵母教学卡片，an en in 与四声练习，强调鼻音收尾和跟读节奏，清晰的儿童学习视觉',negative:'鼻音提示缺失，错误声调，水印，装饰过多',model:'Pinyin Daily',params:'PNG · lesson 12 · 2026 / 10 / 01',caption:'鼻韵母的收尾要从鼻子出气，一口气读完，声音才不会断开。',note:'pinyin-spelling'},
  {id:'pinyin-yw-spell',title:'y、w 的拼写规则',en:'Pinyin / y & w',series:'pinyin',image:'assets/covers/pinyin-yw-spell.png',tags:['y w','整体认读'],prompt:'汉语拼音拼写规则教学卡片，说明 i 行加 y、u 行加 w 的写法，含 yi wu 示例，适合课堂复习',negative:'规则混淆，拼音错误，水印，低可读性',model:'Pinyin Daily',params:'PNG · textbook lesson 09',caption:'i 行前加 y、u 行前加 w，把读音和写法放在同一张卡片里记住。',note:'pinyin-spelling'},
  {id:'math-sine-function',title:'正弦函数的形状',en:'Math Teacher / Sine Function',series:'math-teacher',image:'assets/covers/sin-function-verify-mid.jpg',videoUrl:'assets/videos/sin-function.mp4',videoLabel:'正弦函数视频',tags:['函数','动态可视化'],prompt:'数学教学动画，逐步解释正弦函数的图像，清晰坐标轴、周期、振幅和相位，明亮课堂配色，节奏准确',negative:'坐标轴模糊，标签难读，水印，信息拥挤',model:'Math Teacher',params:'MP4 · 1280 × 900 · 12s',caption:'让曲线动起来，周期、振幅和相位就不再只是公式里的词。',note:'math-motion'},
  {id:'math-rmb-learning',title:'认识人民币',en:'Math Teacher / RMB',series:'math-teacher',image:'assets/covers/rmb-learning-title.jpg',videoUrl:'assets/videos/rmb-learning.mp4',videoLabel:'人民币学习视频',tags:['数学启蒙','生活数学'],prompt:'数学启蒙教学动画，认识人民币面额并进行生活化比较和换算，步骤清楚，适合儿童理解',negative:'金额标注错误，文字难读，水印，节奏过快',model:'Math Teacher',params:'MP4 · 1280 × 720 · 40s',caption:'把金额放回真实生活场景里，比较、换算和使用就有了具体的入口。',note:'math-motion'},
  {id:'math-clock-learning',title:'认识整点',en:'Math Teacher / Clock',series:'math-teacher',image:'assets/covers/clock-learning-title.jpg',videoUrl:'assets/videos/clock-learning-zhengdian.mp4',videoLabel:'认识整点视频',tags:['时间','整点'],prompt:'数学启蒙教学动画，认识钟面和整点时刻，时针分针关系清晰，逐步演示，友好的课堂视觉',negative:'指针位置错误，时间标注错误，水印，背景杂乱',model:'Math Teacher',params:'MP4 · 1280 × 900 · 23s',caption:'从钟面上的两根指针开始，把“整点”变成可以看见和说出的时间关系。',note:'math-motion'}
];
const notes=[
  {id:'pinyin-tone-placement',title:'声调先看位置，再听声音',date:'2026 / 09',type:'拼音方法',intro:'把四声放回韵母上，读音、字形和记忆就有了同一个落点。',body:'制作拼音卡片时，先保证韵母和声调的关系足够清楚，再处理装饰和颜色。孩子可以先看声调位置，再跟着卡片读出来；视觉线索越稳定，复习时越容易自我检查。'},
  {id:'pinyin-spelling',title:'拼读卡片要留出连接感',date:'2026 / 09',type:'拼音方法',intro:'声母、韵母和声调不是三个孤立标签，而是一条可以跟读的声音路径。',body:'一张好的拼读卡片需要让视线从声母自然走到韵母，再落到完整音节。文字不要堆满，示例也不要一次放太多，给孩子留下“连起来读”的空间。'},
  {id:'math-motion',title:'让数学关系动起来',date:'2026 / 10',type:'数学演示',intro:'函数、金额和时间都可以先变成动作，再回到定义和规则。',body:'数学演示先给出一个可观察的变化：曲线沿坐标轴移动、金额在生活场景里组合、指针走到整点。观众先看到关系，再用文字命名它，抽象概念就有了可回看的入口。'}
];
function seriesOf(w){return series.find(s=>s.id===w.series)||series[0]}
function card(w){const s=seriesOf(w);return `<a class="work-card" href="work-detail.html?id=${w.id}" data-series="${w.series}" data-tags="${w.tags.join(' ')}"><div class="work-image"><img src="${w.image}" alt="${w.title} ${s.label}"></div><div class="work-meta"><div><div class="series-label">${s.label}</div><div class="work-title">${w.title}</div>${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><span class="work-index">${String(works.indexOf(w)+1).padStart(2,'0')}</span></div></a>`}
function filterButtons(){return `<button class="filter selected" data-series-filter="all">全部</button>${series.map(s=>`<button class="filter" data-series-filter="${s.id}">${s.label}</button>`).join('')}`}
function initNav(){const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===path||(!path&&a.getAttribute('href')==='index.html'))a.classList.add('active')});const m=document.querySelector('.menu');if(m)m.onclick=()=>document.querySelector('.nav').classList.toggle('open')}
function bindFilters(root,selector='.work-card'){if(!root)return;const buttons=root.querySelectorAll('[data-series-filter]');const cards=root.querySelectorAll(selector);const apply=f=>{buttons.forEach(b=>b.classList.toggle('selected',b.dataset.seriesFilter===f));cards.forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.series!==f));root.querySelectorAll('.series-group').forEach(g=>{const visible=[...g.querySelectorAll('.work-card')].some(c=>!c.classList.contains('hidden'));g.classList.toggle('hidden',!visible)});};buttons.forEach(b=>b.onclick=()=>apply(b.dataset.seriesFilter));return apply}
function renderHome(){const el=document.querySelector('#featured');if(el)el.innerHTML=works.map(card).join('');const home=bindFilters(document.querySelector('#home-archive'));if(home)home(new URLSearchParams(location.search).get('series')||'all');const np=document.querySelector('#notes-preview');if(np)np.innerHTML=notes.map(n=>`<a class="note-item" href="note.html?id=${n.id}"><div class="meta">${n.date} · ${n.type}</div><h3>${n.title}</h3><p>${n.intro}</p></a>`).join('')}
function renderWorks(){const root=document.querySelector('#works-archive');if(!root)return;const gallery=document.querySelector('#gallery');gallery.innerHTML=series.map(s=>{const items=works.filter(w=>w.series===s.id);return `<section class="series-group" data-series-group="${s.id}"><div class="series-heading"><div><div class="eyebrow">${s.en}</div><h2>${s.label}</h2></div><p>${s.description}</p></div><div class="gallery-group">${items.map(card).join('')}</div></section>`}).join('');const apply=bindFilters(root);apply(new URLSearchParams(location.search).get('series')||'all')}
function renderDetail(){const root=document.querySelector('#detail');if(!root)return;const w=works.find(x=>x.id===new URLSearchParams(location.search).get('id'))||works[0];const s=seriesOf(w);document.title=`${w.title} — 溜溜数算 · 影像`;const media=w.videoUrl?`<div class="detail-media"><video controls preload="metadata" poster="${w.image}"><source src="${w.videoUrl}" type="video/mp4">你的浏览器不支持视频播放。</video><p class="media-note">${w.videoLabel||'教学演示视频'}。视频与封面都使用相对路径，放在站点 assets 目录中。</p></div>`:`<img class="detail-hero" src="${w.image}" alt="${w.title}">`;root.innerHTML=`<div class="detail-head"><div><div class="eyebrow">${s.en} / Selected work / ${String(works.indexOf(w)+1).padStart(2,'0')}</div><h1>${w.title}</h1><div><span class="series-pill">${s.label}</span>${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><p class="detail-lead">${w.caption}</p></div>${media}<div class="detail-columns"><div><h2>Prompt / 提示词</h2><div class="prompt-box"><p class="prompt-text">${w.prompt}</p><button class="copy-button" data-copy="${w.prompt.replaceAll('"','&quot;')}">复制提示词</button></div>${w.negative?`<div class="detail-note"><b>Negative prompt</b><br>${w.negative}</div>`:''}</div><div><h2>制作记录</h2><div class="specs"><div class="spec"><span>系列 / Series</span><b>${s.label}</b></div><div class="spec"><span>模型 / Model</span><b>${w.model}</b></div><div class="spec"><span>参数 / Params</span><b>${w.params}</b></div><div class="spec"><span>关键词</span><b>${w.tags.join(' · ')}</b></div>${w.videoUrl?`<div class="spec"><span>视频来源</span><b>assets/videos</b></div>`:''}</div><div class="detail-note">这件作品是「溜溜数算 · 影像」的教学视觉样本。记录参数，不是为了复刻，而是为了保留下一次创作的入口。<br><br><a class="text-link" href="note.html?id=${w.note}">阅读相关笔记 →</a></div></div></div>`;const copy=root.querySelector('.copy-button');if(copy)copy.onclick=async e=>{await navigator.clipboard.writeText(e.currentTarget.dataset.copy);e.currentTarget.textContent='已复制 ✓';e.currentTarget.classList.add('done');setTimeout(()=>{e.currentTarget.textContent='复制提示词';e.currentTarget.classList.remove('done')},1800)}}
function renderNotes(){const el=document.querySelector('#notes-list');if(el)el.innerHTML=notes.map(n=>`<a class="note-row" href="note.html?id=${n.id}"><div class="meta">${n.date}</div><div><h2>${n.title}</h2><div class="meta">${n.type}</div></div><p>${n.intro}</p></a>`).join('')}
function renderNote(){const el=document.querySelector('#note-content');if(!el)return;const n=notes.find(x=>x.id===new URLSearchParams(location.search).get('id'))||notes[0];document.title=`${n.title} — 溜溜数算 · 影像`;el.innerHTML=`<div class="eyebrow">Field note / ${n.date}</div><h1>${n.title}</h1><p class="lede">${n.intro}</p><div class="meta">${n.type} · 溜溜数算</div><h2>先从关系开始</h2><p>${n.body}</p><blockquote>“好的教学视觉，不是把一切都说满，而是为观察和跟读留下空间。”</blockquote><h2>一个小练习</h2><p>打开最近的一张卡片或一段演示，先不看细节，只写下三个词：一个对象词、一个变化词、一个检查词。用它们复述画面，再只替换其中一层。重复三次，你会看到概念如何在同一条线索上变得清楚。</p><p><a class="text-link" href="works.html">回到作品库 →</a></p>`}
document.addEventListener('DOMContentLoaded',()=>{initNav();renderHome();renderWorks();renderDetail();renderNotes();renderNote()});
